### ISSUE TITLE
Missing "spectrum_on_native"

### ISSUE THREAD

**Issue by Oleg-N-Cher** [vilcans/cowgol-firstlook#1]
Please tell what this "spectrum_on_native" is. If it is a folder with files, it would be good to attach it to the project. I couldn't find anything like that in Cowgol distribution. Thanks.

![image](https://github.com/vilcans/cowgol-firstlook/assets/1090608/06b0d753-5a13-4c3e-8b8a-88970d76102c)

**Comment by vilcans** [comment]
I get the same error if I add a file called `test1.cow` and then run `make`. I don't know why it doesn't work, but I remember there was something special about `spectrum_on_native`.

Note that I madde this repo several years ago just to play around a bit with Cowgol (I even [made a video about it](https://www.youtube.com/watch?v=cAoP91QDLy4)). It uses a very old version of Cowgol, so you probably would not want to use this repo as is.

**Comment by Oleg-N-Cher** [comment]
You're right, it's different in the new version. But I couldn't understand how you linked the code for Spectrum. The thing is that Cowgol linker stitches this section into the code:

```
	org 100h <-- a bad start for Spectrum. Address 100h contains the ROM
	lxi sp, TOP+128 <-- it was strange to find 8080 mnemonics here
	call f29___main
	rst 0 <-- a bad end for the Spectrum, a reset.
```

I wrote to David about it, but he has little interest in Spectrum, he's mostly interested in CP/M.
